exportdirectory/base.py, exportdirectory/client.py, exportdirectory/company.py, tests/__init__.py, tests/test_base.py, tests/test_client.py, tests/test_company.py, tests/test_registration.py
[this task](https://uktrade.atlassian.net/browse/ED-147).
=> Add company profile update handler

exportdirectory/company.py, tests/test_company.py
[this task](https://uktrade.atlassian.net/browse/ED-151)
=> Add get company profile handler

exportdirectory/client.py, exportdirectory/company.py, exportdirectory/user.py, tests/test_client.py, tests/test_company.py, tests/test_user.py
[this task](https://uktrade.atlassian.net/browse/ED-179)
=> User profile retrieve and update handlers

directory_api_client/company.py, tests/test_company.py
[this task](https://uktrade.atlassian.net/browse/ED-249)
=> Add call to company number validator

directory_api_client/company.py, tests/test_company.py
[this task](https://uktrade.atlassian.net/browse/ED-245)
=> Add retrieve companies house profile

directory_api_client/base.py, tests/__init__.py, tests/test_base.py
We want to return non-200 responses so the application can handle based on response code using simple if else.
=> Return non-200 responses instead of raising exceptions

directory_api_client/registration.py, tests/test_registration.py
[this task](https://uktrade.atlassian.net/browse/ED-269)
=> Add send verification endpoint

conftest.py, directory_api_client/base.py, makefile, requirements.txt, tests/test_base.py, tests/test_client.py
[this test](https://uktrade.atlassian.net/browse/ED-201)
=> Add the shared signature auth library

CHANGELOG.md, README.md, directory_api_client/buyer.py, directory_api_client/company.py, directory_api_client/enrolment.py, directory_api_client/supplier.py, pull_request_template.md, setup.py, tests/test_company.py
=> Removed fallback cache usage for endpoints can leak user details

CHANGELOG.md, directory_api_client/company.py, setup.py, tests/test_company.py
=> Adding support to register multiple users to company profile

.gitignore, CHANGELOG.md, directory_api_client/buyer.py, directory_api_client/client.py, directory_api_client/company.py, directory_api_client/enrolment.py, directory_api_client/exporting.py, directory_api_client/notifications.py, directory_api_client/supplier.py, directory_api_client/testapiclient.py, setup.py, tests/test_supplier.py, tests/test_testapiclient.py
=> Add a new method to remove self from company profile

CHANGELOG.md, directory_api_client/supplier.py, setup.py, tests/test_supplier.py
=> Add handler for listing supplier sso ids

CHANGELOG.md, README.md, directory_api_client/company.py, directory_api_client/supplier.py, setup.py, tests/test_company.py, tests/test_supplier.py
=> added method `collaborator_invite_list` and renamed existing methods

CHANGELOG.md, directory_api_client/company.py, setup.py, tests/test_company.py
=> added collaborator_invite_delete and collaborator_role_update

CHANGELOG.md, directory_api_client/company.py, setup.py, tests/test_company.py
=> Allow anonymous user retrieving collaboration invite

CHANGELOG.md, directory_api_client/company.py, setup.py, tests/test_company.py
=> Adding authentication to collaborator_create

CHANGELOG.md, directory_api_client/company.py, setup.py, tests/test_company.py
=> TT1910- allow supplier name on invite accept

.circleci/config.yml, .flake8, CHANGELOG.md, directory_api_client/personalisation.py, makefile, setup.py, tests/test_personalisation.py
=> Add user location create handler

CHANGELOG.md, directory_api_client/client.py, setup.py
=> fix expose exportplan client

CHANGELOG.md, directory_api_client/testapiclient.py, setup.py, tests/test_testapiclient.py
=> TT-2288 - add support for custom authenticators

CHANGELOG.md, directory_api_client/client.py, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> add dataservices

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> MVP-310 comtrade data

CHANGELOG.md, directory_api_client/personalisation.py, setup.py, tests/test_personalisation.py
=> MVP-384 add recommended countries

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-125 update api

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> Add objectives delete endpoint

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> GP2-169- load-IMF-Data

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> GP2-188 add target research data

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-315 add route to make end-points

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-339-add-adaption-tm-documents

CHANGELOG.md, directory_api_client/company.py, setup.py, tests/test_company.py
=> Added delete endpoint for company

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Added endpoint for target market data

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Amended reqest param for PopulationByCountry endpoint

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Added ecomony comtrade data endpoint

CHANGELOG.md, directory_api_client/dataservices.py, directory_api_client/personalisation.py, setup.py, tests/test_dataservices.py, tests/test_personalisation.py
=> Moved SuggestedCountries to dataservices

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Refactor for ComTrade endpoint

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Add endpoint for society data

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> added trading blocs api to client

.circleci/config.yml, CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-1180-travel-bus-BE 

.circleci/config.yml
=> upgrade pip on pypi publish

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> GP2-1709-trade-barrier-integration

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-2401-add-upload-pdf-method

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=>  GP2-2856-remove-unused-api-calls 

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-3173-multi-Export-plan-list

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-3275 - Export-plan-delete

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> GP2-3275 - Export plan delete - 2

CHANGELOG.md, setup.py
A PR to get this version bump published to pypi
=> GP2-3275 Export plan delete - to publish

CHANGELOG.md, setup.py
=> GP2-3275 Export plan delete - publish attempt 3

CHANGELOG.md, setup.py
=> No-ticket-test-publish

CHANGELOG.md, directory_api_client/exportplan.py
=> GP2-3341-fix-ep-caching 

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> GP2-3123-remove-redundant-code 

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
Data services methods to fetch market trends & trade highlights for a particular country.
To do:
=> Data services' market trends & trade highlights

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Top five goods client endpoint

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> GLS-186 filtered endpoints - remove unused year parameter

CHANGELOG.md, setup.py
=> Increase directory_client_core version for Django 3.2 upgrade

CHANGELOG.md, directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Add UK's FTAs endpoint to dataservices

CHANGELOG.md, setup.py
This PR pins the `wheel` package to a secure version.
=> Upgrade wheel package to 0.38.1

setup.py
Adds package version to setup.py, which I missed in PR #167.
=> Update missing package version

.gitignore, setup.py
=> use latest deps

directory_api_client/dataservices.py, tests/test_dataservices.py
Update dataservices endpoints to correspond with new directory-api Business Cluster Information endpoints.
Ticket - https://uktrade.atlassian.net/browse/IOO-1125
Directory API PR - https://github.com/uktrade/directory-api/pull/1257
=> IOO-1125 - update endpoints for bci data

directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> Iguk 200 dbt sector list

directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
Add endpoint for GVA bandings lookup.
https://uktrade.atlassian.net/browse/IGUK-179
=> IGUK-179 GVA bandings

CHANGELOG.md, directory_api_client/exportplan.py, setup.py, tests/test_exportplan.py
=> dont cache exportplan gets

directory_api_client/dataservices.py, setup.py, tests/test_dataservices.py
=> BGST-228 growth hub finder
